// src/lib/components/Characters.svelte
<script>
    import Character from './Character.svelte';

    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
</script>

<div class="characters-wrapper">
    {#each characters as char}
        <Character {char} />
    {/each}
</div>

<style>
    .characters-wrapper {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }
</style>

// src/components/search/characters.jsx
import React from 'react';
import Character from './character';

const Characters = ({ handleOnClick }) => {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
    return characters.map(character => (
        <Character key={character} char={character} handleOnClick={handleOnClick} />
    ));
};

export default Characters;
